-- Copyright (C) 2025-2026 NORCE Research AS
-- This deck was generated by pofff https://github.com/cssr-tools/pofff
----------------------------------------------------------------------------
RUNSPEC
----------------------------------------------------------------------------
DIMENS 
${dic['nxz'][0]} 1 ${dic['nxz'][1]} /

EQLDIMS
/

TABDIMS
7 /

WATER
GAS
CO2STORE
DISGASW
DIFFUSE

METRIC

START
1 JAN 2025 /

UNIFOUT
----------------------------------------------------------------------------
GRID
----------------------------------------------------------------------------
INIT

% if dic["grid"] == 'corner-point':
INCLUDE
'${dic['deck']}/GRID.INC' /
% elif dic["grid"] == 'tensor':
INCLUDE
'${dic['deck']}/DX.INC' /

DY 
${dic['nxz'][0]*dic['nxz'][1]}*${dic['dims'][1]} /

INCLUDE
DZ.INC /

TOPS
${dic['nxz'][0]}*0 /
% else:
DX 
${dic['nxz'][0]*dic['nxz'][1]}*${dic['dims'][0] / dic['nxz'][0]} /

DY 
${dic['nxz'][0]*dic['nxz'][1]}*${dic['dims'][1]} /

DZ 
${dic['nxz'][0]*dic['nxz'][1]}*${dic['dims'][2] / dic['nxz'][1]} /

TOPS
${dic['nxz'][0]}*0 /
% endif

INCLUDE
'${dic['deck']}/FLUXNUM.INC' /

DISPERC
${dic['nxz'][0]*dic['nxz'][1]}*0 /

INCLUDE
EQUALREG.INC /

BCCON 
1 1 ${dic['nxz'][0]} 1 1 1 1 Z- /
/
% if dic["multpv"]:
% for name in ["MULTPV", "MULTX", "MULTX-", "MULTZ", "MULTZ-"]:
INCLUDE
'${dic['deck']}/${name}.INC' /
% endfor
% endif
% if "thicknessmult" in dic["hm"]:
----------------------------------------------------------------------------
EDIT
----------------------------------------------------------------------------
INCLUDE
THICKNESSMULT.INC /
% endif
----------------------------------------------------------------------------
PROPS
----------------------------------------------------------------------------
INCLUDE
TABLES.INC /
% if (dic["diffusion"][0] + dic["diffusion"][1]) > 0:

DIFFAWAT
${dic["diffusion"][0]} ${dic["diffusion"][0]} /

DIFFAGAS
${dic["diffusion"][1]} ${dic["diffusion"][1]} /
% endif

THCO2MIX
NONE NONE NONE /
----------------------------------------------------------------------------
REGIONS
----------------------------------------------------------------------------
COPY
FLUXNUM SATNUM /
/

INCLUDE
'${dic['deck']}/FIPNUM.INC' /
----------------------------------------------------------------------------
SOLUTION
----------------------------------------------------------------------------
EQUIL
0 ${dic['pressure']/1.e5} 0 0 0 0 1 1 0 /

RPTRST
BASIC=2 DEN PCGW RSWSAT /

RTEMPVD
0   ${dic["temperature"][1]}
${dic['dims'][2]} ${dic["temperature"][0]} /
----------------------------------------------------------------------------
SUMMARY
----------------------------------------------------------------------------
PERFORMA
FGMIP
FGMIR
FGMIT
RGKDI
/
RGKDM
/
RGIP
/
RWCD
/
WBHP
/
WGIR
/
WGIT
/
BWPR
% for sensor in dic["sensor_ik"]: 
${sensor[0]+1} 1 ${sensor[1]+1} /
% endfor
/
----------------------------------------------------------------------------
SCHEDULE
----------------------------------------------------------------------------
RPTRST
BASIC=2 DEN PCGW RSWSAT /

INCLUDE
BCPROP.INC /
% for j in range(len(dic['inj'])):

% if dic["tuning"]:
TUNING
${dic['inj'][j][4]+" " if len(dic['inj'][j])>4 else ""}/
${dic['inj'][j][5]+" " if len(dic['inj'][j])>5 else ""}/
${dic['inj'][j][6]+" " if len(dic['inj'][j])>6 else ""}/
% endif
SOURCE
% for i in range(len(dic['source_ik'])):
${dic['source_ik'][i][0]} 1 ${dic['source_ik'][i][1]} GAS ${f"{dic['inj'][j][2+i] * 86400:E}"} /
% endfor
/
TSTEP
<% no_steps = round(dic['inj'][j][0]/dic['inj'][j][1])%>\
${f"{no_steps}*" if no_steps > 1 else ""}${dic['inj'][j][1] / 86400.} /
% endfor