-- Copyright (C) 2025-2026 NORCE Research AS
-- This deck was generated by pofff https://github.com/cssr-tools/pofff
----------------------------------------------------------------------------
RUNSPEC
----------------------------------------------------------------------------
DIMENS 
${nxz[0]} 1 ${nxz[1]} /

EQLDIMS
/

TABDIMS
7 /

WATER
GAS
CO2STORE
DISGASW
DIFFUSE

METRIC

START
1 JAN 2025 /

UNIFOUT
----------------------------------------------------------------------------
GRID
----------------------------------------------------------------------------
INIT

% if grid == 'corner-point':
INCLUDE
'${deck}/GRID.INC' /
% elif grid == 'tensor':
INCLUDE
'${deck}/DX.INC' /

DY 
${nxz[0]*nxz[1]}*${dims[1]} /

INCLUDE
DZ.INC /

TOPS
${nxz[0]}*0 /
% else:
DX 
${nxz[0]*nxz[1]}*${dims[0] / nxz[0]} /

DY 
${nxz[0]*nxz[1]}*${dims[1]} /

DZ 
${nxz[0]*nxz[1]}*${dims[2] / nxz[1]} /

TOPS
${nxz[0]}*0 /
% endif

INCLUDE
'${deck}/FLUXNUM.INC' /

DISPERC
${nxz[0]*nxz[1]}*0 /

INCLUDE
EQUALREG.INC /

BCCON 
1 1 ${nxz[0]} 1 1 1 1 Z- /
/
% if multpv:
% for name in ["MULTPV", "MULTX", "MULTX-", "MULTZ", "MULTZ-"]:
INCLUDE
'${deck}/${name}.INC' /
% endfor
% endif
% if "thicknessmult" in hm:
----------------------------------------------------------------------------
EDIT
----------------------------------------------------------------------------
INCLUDE
THICKNESSMULT.INC /
% endif
----------------------------------------------------------------------------
PROPS
----------------------------------------------------------------------------
INCLUDE
TABLES.INC /
% if (diffusion[0] + diffusion[1]) > 0:

DIFFAWAT
${diffusion[0]} ${diffusion[0]} /

DIFFAGAS
${diffusion[1]} ${diffusion[1]} /
% endif

THCO2MIX
NONE NONE NONE /
----------------------------------------------------------------------------
REGIONS
----------------------------------------------------------------------------
COPY
FLUXNUM SATNUM /
/

INCLUDE
'${deck}/FIPNUM.INC' /
----------------------------------------------------------------------------
SOLUTION
----------------------------------------------------------------------------
EQUIL
0 ${pressure/1.e5} 0 0 0 0 1 1 0 /

RPTRST
BASIC=2 DEN PCGW RSWSAT /

RTEMPVD
0   ${temperature[1]}
${dims[2]} ${temperature[0]} /
----------------------------------------------------------------------------
SUMMARY
----------------------------------------------------------------------------
PERFORMA
FGMIP
FGMIR
FGMIT
RGKDI
/
RGKDM
/
RGIP
/
RWCD
/
WBHP
/
WGIR
/
WGIT
/
BWPR
% for sensor in sensor_ik: 
${sensor[0]+1} 1 ${sensor[1]+1} /
% endfor
/
----------------------------------------------------------------------------
SCHEDULE
----------------------------------------------------------------------------
RPTRST
BASIC=2 DEN PCGW RSWSAT /

INCLUDE
BCPROP.INC /
% for j in range(len(inj)):

% if tuning:
TUNING
${inj[j][4]+" " if len(inj[j])>4 else ""}/
${inj[j][5]+" " if len(inj[j])>5 else ""}/
${inj[j][6]+" " if len(inj[j])>6 else ""}/
% endif
SOURCE
% for i in range(len(source_ik)):
${source_ik[i][0]} 1 ${source_ik[i][1]} GAS ${f"{inj[j][2+i] * 86400:E}"} /
% endfor
/
TSTEP
<% no_steps = round(inj[j][0]/inj[j][1])%>\
${f"{no_steps}*" if no_steps > 1 else ""}${inj[j][1] / 86400.} /
% endfor