# SPDX-FileCopyrightText: 2025-2026 NORCE Research AS
# SPDX-License-Identifier: GPL-3.0
# pylint: disable=R0912, R0914

"""Utility functions to write OPM/pofff files and variables."""

import os
import subprocess
from mako.template import Template
import numpy as np
from numpy.typing import NDArray

from pofff.config.config import PofffConfig

HEADER = (
    "-- Copyright (C) 2025-2026 NORCE Research AS\n"
    "-- This deck was generated by pofff https://github.com/cssr-tools/pofff\n"
)


def compact_format(values: list) -> list:
    """Encode values using Eclipse-style n*value compaction.
    Uses NumPy for efficient run-length encoding."""
    if len(values) == 0:
        return []
    v = np.asarray(values, dtype=np.float64)
    change = np.concatenate(([True], v[1:] != v[:-1]))
    idx = np.flatnonzero(change)
    counts = np.diff(np.append(idx, v.size))
    uniq = v[idx]
    out = []
    for val, n in zip(uniq, counts):
        if n > 1:
            if val == 0:
                out.append(f"{n}*0 ")
            elif val.is_integer():
                out.append(f"{n}*{int(val)} ")
            else:
                out.append(f"{n}*{val} ")
        else:
            if val == 0:
                out.append("0 ")
            elif val.is_integer():
                out.append(f"{int(val)} ")
            else:
                out.append(f"{val} ")
    return out


def create_corner_point_grid(
    cfg: PofffConfig, xcoord: NDArray, zcoord: NDArray
) -> None:
    """Write COORD and ZCORN sections for a corner-point grid.
    Output is bit-identical to the original implementation."""

    nx, nz = cfg.nxz
    nk = nz + 1
    grid = []
    grid.append("COORD\n")
    tmp = []
    for y in [0, cfg.dims[1]]:
        for i in range(nx + 1):
            base = i * nk
            tmp.append(f"{xcoord[base]:E} {y} 0 " f"{xcoord[base + nz]:E} {y:E} 0 ")
    grid.extend(compact_format("".join(tmp).split()))
    grid.append("/\n")
    grid.append("ZCORN\n")
    tmp = []
    for i in range(nx):
        tmp.append(f"{zcoord[i*nk]:E} {zcoord[(i+1)*nk]:E} ")
    tmp.extend(tmp[-nx:])
    for k in range(nz - 1):
        for i in range(nx):
            base = i * nk + k + 1
            tmp.append(f"{zcoord[base]:E} {zcoord[base + nk]:E} ")
        tmp.extend(tmp[-nx:])
        tmp.extend(tmp[-2 * nx :])
    for i in range(nx):
        tmp.append(f"{zcoord[(i+1)*nk - 1]:E} {zcoord[(i+2)*nk - 1]:E} ")
    tmp.extend(tmp[-nx:])
    grid.extend(compact_format("".join(tmp).split()))
    grid.append("/")
    with open(f"{cfg.deck}/GRID.INC", "w", encoding="utf8") as f:
        f.write(HEADER)
        f.write("".join(grid))
        f.write("\n")


def write_keywords(cfg: PofffConfig) -> None:
    """Write OPM keyword include files (FIPNUM, FLUXNUM, DX, DZ, etc.)."""
    keywords = ["fluxnum", "fipnum"]
    if cfg.grid == "tensor":
        keywords += ["dx", "dz"]
    if cfg.thickness in ("initial", "final"):
        keywords += ["multpv", "multx", "multx-", "multz", "multz-"]
    for name in keywords:
        values = getattr(cfg, "multpv" if name.startswith("mult") else name)
        body = compact_format(values)
        with open(f"{cfg.deck}/{name.upper()}.INC", "w", encoding="utf8") as f:
            f.write(HEADER)
            f.write(f"{name.upper()}\n")
            f.writelines(body)
            f.write("/\n")


def write_files(cfg: PofffConfig) -> None:
    """Generate all OPM, ERT, and Everest files using mako templates."""
    write_keywords(cfg)
    tmpl = Template(filename=f"{cfg.path}/templates/deck.mako")
    mytemplate = tmpl.render(
        nxz=cfg.nxz,
        grid=cfg.grid,
        deck=cfg.deck,
        dims=cfg.dims,
        diffusion=cfg.diffusion,
        multpv=cfg.multpv,
        hm=cfg.hm,
        pressure=cfg.pressure,
        temperature=cfg.temperature,
        sensor_ik=cfg.sensor_ik,
        source_ik=cfg.source_ik,
        inj=cfg.inj,
        tuning=cfg.tuning,
    )
    with open(f"{cfg.deck}/{cfg.data}.DATA", "w", encoding="utf8") as f:
        f.write(mytemplate)
    job_names = ["bcprop", "equalreg", "satufunc"]
    render_bcprop(cfg)
    render_equalreg(cfg)
    render_satufunc(cfg)
    if cfg.everert:
        render_flow(cfg)
        render_copyd(cfg)
        job_names += ["flow", "copyd"]
        if cfg.popsize:
            job_names += ["scale"]
            render_scale(cfg)
            with open(f"{cfg.jobs}/METRIC", "w", encoding="utf8") as f:
                f.write("EXECUTABLE metric.py")

            with open(f"{cfg.jobs}/DATA", "w", encoding="utf8") as f:
                f.write("EXECUTABLE data.py")
            render_everest(cfg)
        else:
            with open(f"{cfg.jobs}/METRIC", "w", encoding="utf8") as f:
                f.write("EXECUTABLE metric.py\n")
                f.write(
                    f"ARGLIST -t {cfg.times} -e {cfg.experiment} "
                    f"-s {cfg.msat} -c {cfg.mcon} -p {cfg.path}"
                )
            with open(f"{cfg.jobs}/DATA", "w", encoding="utf8") as f:
                f.write("EXECUTABLE data.py\n")
                f.write(f"ARGLIST -t {cfg.times} -m {cfg.deck}/cellmap.npy")
            render_ert(cfg)
        if cfg.monotonic:
            render_monotonic(cfg)
            job_names += ["monotonic"]
    for name in job_names:
        script_path = f"{cfg.jobs}/{name}.py"
        os.chmod(script_path, 0o755)
        if cfg.mode in ["single", "files"] and not cfg.everert:
            subprocess.run(["python3", script_path], check=True)
            os.remove(script_path)
    if cfg.ertargs and cfg.everert:
        assert cfg.errors
        with open(f"{cfg.deck}/obs.txt", "w", encoding="utf8") as f:
            f.write("\n".join(f"0 {error}" for error in cfg.errors) + "\n")
        with open(f"{cfg.deck}/para.txt", "w", encoding="utf8") as f:
            f.write(
                "\n".join(
                    f"{para} {cfg.hm[para][0].upper()} {cfg.hm[para][1]} {cfg.hm[para][2]}"
                    for para in cfg.hm
                )
                + "\n"
            )
        content = "{\n" + ",\n".join(f'"{para}": <{para}>' for para in cfg.hm) + "\n}\n"
        with open(f"{cfg.deck}/prior.tmpl", "w", encoding="utf8") as f:
            f.write(content)


def render_monotonic(cfg: PofffConfig) -> None:
    """Generate monotonic.py"""
    inc_names = ["swi", "sni", "pen", "nkrw", "nkrn", "npe"]
    dec_names = ["perm", "permx", "permz", "disperc"]

    inc_lines = []
    for name in inc_names:
        keys = [f"{name}{i}" for i in range(1, 8) if f"{name}{i}" in cfg.hm]
        for prev, cur in zip(keys, keys[1:]):
            inc_lines.append(
                f"if coef['{prev}'] < coef['{cur}']:\n" f"    nomonotonic = True"
            )

    dec_lines = []
    for name in dec_names:
        keys = [f"{name}{i}" for i in reversed(range(1, 8)) if f"{name}{i}" in cfg.hm]
        for prev, cur in zip(keys, keys[1:]):
            dec_lines.append(
                f"if coef['{prev}'] < coef['{cur}']:\n" f"    nomonotonic = True"
            )

    increasing_block = "\n".join(inc_lines)
    decreasing_block = "\n".join(dec_lines)

    tmpl = Template(filename=f"{cfg.path}/templates/monotonic.mako")
    with open(f"{cfg.jobs}/monotonic.py", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                increasing_block=increasing_block,
                decreasing_block=decreasing_block,
            )
        )


def render_scale(cfg: PofffConfig) -> None:
    """Generate scale.py"""
    parts = []

    keys = list(cfg.hm.keys())

    for i, p in enumerate(keys):
        lo, hi, scale = cfg.hm[p][1], cfg.hm[p][2], cfg.hm[p][3]

        expr = f"{lo}+coef['{p}']*({hi}-{lo})/(1.0*{scale})"

        comma = "," if i < len(keys) - 1 else ""

        parts.append(f'    para += f"\\"{p}\\":"\n' f'    para += f"{{{expr}}}{comma}"')

    para_block = "\n".join(parts)

    tmpl = Template(filename=f"{cfg.path}/templates/scale.mako")
    with open(f"{cfg.jobs}/scale.py", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                para_block=para_block,
            )
        )


def render_bcprop(cfg: PofffConfig) -> None:
    """Generate bcprop.py"""
    imports_block = ""

    if cfg.monotonic:
        imports_block += "import sys\n"
        if cfg.everert:
            imports_block += "import os\n"

    if cfg.everert:
        imports_block += "import json"
    else:
        imports_block += "import os"

    monotonic_block = (
        '    if os.path.exists("NOMONOTONIC"):\n' "        sys.exit()\n"
        if cfg.monotonic
        else ""
    )

    if cfg.everert:
        coef_block = (
            '    with open("para.json", "r", encoding="utf8") as f:\n'
            "        coef = json.load(f)\n"
        )
        bcprop_path = '"BCPROP.INC"'
    else:
        coef_block = ""
        bcprop_path = f"os.path.join('{cfg.fol}', \"BCPROP.INC\")"

    if cfg.everert and "pen1" in cfg.hm:
        if cfg.popsize:
            lo, hi, scale = cfg.hm["pen1"][1], cfg.hm["pen1"][2], cfg.hm["pen1"][3]
            val = f"({cfg.pressure}+{lo}+coef['pen1']*({hi}-{lo})/(1.0*{scale}))"
        else:
            val = f"({cfg.pressure}+coef['pen1'])"
    else:
        val = f"({cfg.pressure}+{cfg.para['pen1']})"

    bc_line = f'        file.write(f"1 DIRICHLET WATER 1* {{{val}/1.e5}} /\\n")\n'

    thickness_block = ""

    if cfg.everert and "thicknessmult" in cfg.hm:
        if cfg.popsize:
            lo, hi, scale = (
                cfg.hm["thicknessmult"][1],
                cfg.hm["thicknessmult"][2],
                cfg.hm["thicknessmult"][3],
            )
            mult_val = f"{lo}+coef['thicknessmult']*({hi}-{lo})/(1.0*{scale})"
        else:
            mult_val = "coef['thicknessmult']"

        size = cfg.nxz[0] * cfg.nxz[1]

        lines = ['    with open("THICKNESSMULT.INC", "w", encoding="utf8") as file:']

        for name in ["PV", "X", "X-", "Z", "Z-"]:
            lines.append(f'        file.write("MULT{name}\\n")')
            lines.append(f'        file.write(f"{size}*{{{mult_val}}} /\\n")')

        thickness_block = "\n".join(lines)

    tmpl = Template(filename=f"{cfg.path}/templates/bcprop.mako")
    with open(f"{cfg.jobs}/bcprop.py", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                imports_block=imports_block,
                monotonic_block=monotonic_block,
                coef_block=coef_block,
                bcprop_path=bcprop_path,
                bc_line=bc_line,
                thickness_block=thickness_block,
            )
        )


def render_copyd(cfg: PofffConfig) -> None:
    """Generate copyd.py"""
    monotonic_block = (
        'if os.path.exists("NOMONOTONIC"):\n' "    sys.exit()\n"
        if cfg.monotonic
        else ""
    )

    tmpl = Template(filename=f"{cfg.path}/templates/copyd.mako")
    with open(f"{cfg.jobs}/copyd.py", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                monotonic_block=monotonic_block,
                deck=cfg.deck,
            )
        )


def render_flow(cfg: PofffConfig) -> None:
    """Generate flow.py"""
    monotonic_block = (
        'if os.path.exists("NOMONOTONIC"):\n' "    sys.exit()\n"
        if cfg.monotonic
        else ""
    )

    cmd_parts = [f"'{x}'" for x in cfg.flow.split(" ")]
    cmd_str = f"[{', '.join(cmd_parts)}, '{cfg.data}']"

    if cfg.maxtime is not None:
        run_block = f"    p = subprocess.run({cmd_str}, timeout={cfg.maxtime})\n"
    else:
        run_block = f"    p = subprocess.run({cmd_str})\n"

    delete_block = ""
    if cfg.delete:
        delete_block = "\n".join(
            [
                (
                    '    for suff in ["INC", "EGRID", "DBG", "PRT", "SMSPEC", "UNRST", '
                    '"UNSMRY", "INIT", "ESMRY", "DATA"]:'
                ),
                '        os.system(f"rm -rf *.{suff}")',
                '    for pref in ["thickness_eval","metr_eval","safu_eval","poro_eval"]:',
                '        os.system(f"rm -rf {pref}.*")',
            ]
        )

    tmpl = Template(filename=f"{cfg.path}/templates/flow.mako")
    with open(f"{cfg.jobs}/flow.py", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                monotonic_block=monotonic_block,
                run_block=run_block,
                delete_block=delete_block,
            )
        )


def render_equalreg(cfg: PofffConfig) -> None:
    """Generate equalreg.py"""
    imports_block = ""

    if cfg.monotonic:
        imports_block += "import sys\n"
        if cfg.everert:
            imports_block += "import os\n"

    if cfg.everert:
        imports_block += "import json"
    else:
        imports_block += "import os"

    monotonic_block = (
        '    if os.path.exists("NOMONOTONIC"):\n' "        sys.exit()\n"
        if cfg.monotonic
        else ""
    )

    if cfg.everert:
        coef_block = (
            '    with open("para.json", "r", encoding="utf8") as f:\n'
            "        coef = json.load(f)\n"
        )
        output_path = '"EQUALREG.INC"'
    else:
        coef_block = ""
        output_path = f"os.path.join('{cfg.fol}', \"EQUALREG.INC\")"

    names = [
        ("poro", "poro"),
        ("permx", "permx"),
        ("permy", "permx"),
        ("permz", "permz"),
        ("disperc", "disperc"),
    ]

    lines = []

    for i in range(1, 8):
        for name, key in names:
            hm_key = f"{name}{i}"
            perm_key = f"perm{i}"
            val = None

            if cfg.everert:
                if hm_key in cfg.hm:
                    if cfg.popsize:
                        lo, hi, scale = (
                            cfg.hm[hm_key][1],
                            cfg.hm[hm_key][2],
                            cfg.hm[hm_key][3],
                        )
                        val = f"{lo}+coef['{hm_key}']*({hi}-{lo})/(1.0*{scale})"
                    else:
                        val = f"coef['{hm_key}']"

                elif name in ("permx", "permy", "permz") and perm_key in cfg.hm:
                    if cfg.popsize:
                        lo, hi, scale = (
                            cfg.hm[perm_key][1],
                            cfg.hm[perm_key][2],
                            cfg.hm[perm_key][3],
                        )
                        val = f"{lo}+coef['{perm_key}']*({hi}-{lo})/(1.0*{scale})"
                    else:
                        val = f"coef['{perm_key}']"

            if val is None:
                val = cfg.para[f"{key}{i}"]

            lines.append(f'        file.write(f"{name.upper()} {{{val}}} {i} F /\\n")')

    body_block = "\n".join(lines)

    tmpl = Template(filename=f"{cfg.path}/templates/equalreg.mako")
    with open(f"{cfg.jobs}/equalreg.py", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                imports_block=imports_block,
                monotonic_block=monotonic_block,
                coef_block=coef_block,
                output_path=output_path,
                body_block=body_block,
            )
        )


def render_satufunc(cfg: PofffConfig) -> None:
    """Generate satufunc.py"""
    imports_block = ""
    if cfg.monotonic:
        imports_block += "import os\nimport sys\n"
    if cfg.everert:
        imports_block += "import json"

    monotonic_block = (
        '    if os.path.exists("NOMONOTONIC"):\n' "        sys.exit()\n"
        if cfg.monotonic
        else ""
    )

    coef_block = (
        '    with open("para.json", "r", encoding="utf8") as f:\n'
        "        coef = json.load(f)\n"
        if cfg.everert
        else ""
    )

    tables_path = '"TABLES.INC"' if cfg.everert else f'"{cfg.fol}/TABLES.INC"'

    names = ["swi", "sni", "pen", "nkrw", "nkrn", "npe", "thre", "npnt"]
    rows = []

    for i in range(1, 8):
        vals = []
        for name in names:
            key = f"{name}{i}"
            val = None

            if cfg.everert and key in cfg.hm:
                if cfg.popsize:
                    lo, hi, scale = (
                        cfg.hm[key][1],
                        cfg.hm[key][2],
                        cfg.hm[key][3],
                    )
                    val = f"{lo}+coef['{key}']*({hi}-{lo})/(1.0*{scale})"
                else:
                    val = f"coef['{key}']"

            if val is None:
                val = cfg.para[key]

            vals.append(val)

        rows.append(f"    safu[{i-1}] = [{', '.join(map(str, vals))}]")

    safu_block = "\n".join(rows)

    tmpl = Template(filename=f"{cfg.path}/templates/satufunc.mako")
    with open(f"{cfg.jobs}/satufunc.py", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                imports_block=imports_block,
                krw_expr=cfg.krw.strip(),
                krn_expr=cfg.krn.strip(),
                cap_expr=cfg.cap.strip(),
                monotonic_block=monotonic_block,
                coef_block=coef_block,
                safu_block=safu_block,
                tables_path=tables_path,
            )
        )


def render_ert(cfg: PofffConfig) -> None:
    """Generate ert.txt"""
    names = ["copyd", "equalreg", "satufunc", "bcprop", "flow"]
    lines = []
    for name in names:
        lines.append(f"INSTALL_JOB {name} ./jobs/{name.upper()}")
        lines.append(f"FORWARD_MODEL {name}")
    jobs_block = "\n".join(lines)
    random_seed_block = (
        f"RANDOM_SEED {cfg.random_seed}" if cfg.random_seed is not None else ""
    )
    delete_block = ""
    if cfg.delete:
        delete_block = "INSTALL_JOB delete ./jobs/DELETE\nFORWARD_MODEL delete"
    tmpl = Template(filename=f"{cfg.path}/templates/ert.mako")
    rendered = tmpl.render(
        ensembles=cfg.ensembles,
        min_realizations_success=cfg.min_realizations_success,
        cores=cfg.cores,
        random_seed=cfg.random_seed,
        enkf_alpha=cfg.enkf_alpha,
        delete=cfg.delete,
        jobs_block=jobs_block,
        random_seed_block=random_seed_block,
        delete_block=delete_block,
    )
    with open(f"{cfg.fol}/ert.txt", "w", encoding="utf8") as f:
        f.write(rendered)


def render_everest(cfg: PofffConfig) -> None:
    """Generate everest.yml"""
    variables_block = "\n".join(
        [
            f"      - name: {p}\n"
            f"        max: {cfg.hm[p][3]}\n"
            f"        initial_guess: "
            f"{round((cfg.hm[p][0]-cfg.hm[p][1])/((cfg.hm[p][2]-cfg.hm[p][1])/(1.0*cfg.hm[p][3])))}"
            for p in cfg.hm
        ]
    )

    options_names = [
        "strategy",
        "maxiter",
        "popsize",
        "tol",
        "mutation",
        "recombination",
        "rng",
        "callback",
        "disp",
        "polish",
        "init",
        "atol",
        "updating",
        "workers",
        "constraints",
        "x0",
        "integrality",
        "vectorized",
    ]

    options_block = "\n".join(
        [f"    {n}: {getattr(cfg, n)}" for n in options_names if getattr(cfg, n)]
    )

    install_jobs_block = (
        (
            "\n".join(
                [
                    "  - name: scale",
                    "    executable: jobs/scale.py",
                    "  - name: monotonic",
                    "    executable: jobs/monotonic.py",
                ]
            )
            + "\n"
        )
        if cfg.monotonic
        else ""
    ) + "\n".join(
        [
            f"  - name: {n}\n    executable: jobs/{n}.py"
            for n in [
                "copyd",
                "equalreg",
                "satufunc",
                "bcprop",
                "flow",
                "data",
                "metric",
                "delete",
            ]
        ]
    )

    forward_block = (
        (("\n".join(["  - scale", "  - monotonic"]) + "\n") if cfg.monotonic else "")
        + "\n".join(
            [
                "  - copyd",
                "  - equalreg",
                "  - satufunc",
                "  - bcprop",
                "  - flow",
                (
                    "  - data"
                    f"        -t {cfg.times}\n"
                    f"                -m {cfg.deck}/cellmap.npy"
                ),
                (
                    "  - metric"
                    f"      -t {cfg.times}\n"
                    f"                -e {cfg.experiment}\n"
                    f"                -p {cfg.path}\n"
                    f"                -s {cfg.msat}\n"
                    f"                -c {cfg.mcon}"
                ),
            ]
        )
        + ("\n  - delete" if cfg.delete else "")
    )

    max_batch_block = (
        f"\n  max_batch_num: {cfg.max_batch_num}" if cfg.max_batch_num else ""
    )

    rng_block = f"  random_seed: {cfg.rng}" if cfg.rng else ""

    tmpl = Template(filename=f"{cfg.path}/templates/everest.mako")
    with open(f"{cfg.fol}/everest.yml", "w", encoding="utf8") as f:
        f.write(
            tmpl.render(
                variables_block=variables_block,
                max_function_evaluations=cfg.max_function_evaluations,
                min_realizations_success=cfg.min_realizations_success,
                max_batch_block=max_batch_block,
                options_block=options_block,
                install_jobs_block=install_jobs_block,
                cores=cfg.cores,
                forward_block=forward_block,
                rng_block=rng_block,
            )
        )
