# pofff -i everest_iter_3.toml -o everest_iter_3 -m everest -t 24,48,72,96,120
# Set the full path to the flow executable and flags
flow="flow --newton-min-iterations=1 --solver-max-restarts=20 --time-step-control=newtoniterationcount --solver-growth-factor=1.6 --linear-solver=cpr_trueimpes --time-step-control-growth-rate=1.1 --solver-restart-factor=0.5 --time-step-control-decay-rate=0.65 --enable-opm-rst-file=true"

# Set the model parameters
grid="corner-point" # Type of grid (cartesian, tensor, or corner-point)
thickness="final" # Thickness maps (measured 'initial', 'final', or a real positive value)
mult_thickness=1 # Thickness multiplier (a real positive value)
x=[140] # If cartesian, number of x cells [-]; otherwise, variable array of x-refinement
z=[7,5,5,5,5,5,5,8,10,9,5] # If cartesian, number of z cells [-]; if tensor, variable array of z-refinement; if corner-point, fix array of z-refinement (18 entries)
temperature=[20, 20] # Temperature bottom and top rig [C]
pressure=104900 # Pressure at the datum [Pa]           
diffusion=[1e-9, 2e-8] # Diffusion (in liquid and gas) [m^2/s]
sources=[[0.9, 0.3], [1.7, 0.7]] # Source positions: x and z coordinates [m], source 1 to 2

# Schedule: 1) injection time [s], 2) time step size to write results [s], 3) injection rate [kg/s] (source1), and 4) injection rate [kg/s] (source2)
inj=[[8100, 8100, 3E-7, 0, '1e-2 3e-4 1e-20 1e-20 1.6 0.2 0.65 1.1'], 
[10200, 10200, 3E-7, 3E-7, '1e-2 1e-4 1e-20 1e-20 1.6 0.2 0.65 1.1'], 
[68100, 68100, 0, 0, '1e-2 1e-3 1e-20 1e-20 1.6 0.2 0.65 1.1'], 
[345600, 86400, 0, 0, '1e-2 1e-2 1e-20 1e-20 1.6 0.2 0.65 1.1']]

# Facie Properties
facie1={"permx1"=62000,"permz1"=62000,"poro1"=0.37,"disperc1"=0,"swi1"=0.3425,"sni1"=0.25,"pen1"=1900,"nkrw1"=2,"nkrn1"=2,"npe1"=2,"thre1"=5e-2,"npnt1"=100}
facie2={"permx2"=152000,"permz2"=152000,"poro2"=0.38,"disperc2"=0,"swi2"=0.32,"sni2"=0.2,"pen2"=950,"nkrw2"=2,"nkrn2"=2,"npe2"=2,"thre2"=5e-2,"npnt2"=100}
facie3={"permx3"=428000,"permz3"=428000,"poro3"=0.40,"disperc3"=0,"swi3"=0.293,"sni3"=0.077,"pen3"=185,"nkrw3"=2,"nkrn3"=2,"npe3"=2,"thre3"=5e-2,"npnt3"=100}
facie4={"permx4"=1120000,"permz4"=1120000,"poro4"=0.39,"disperc4"=0,"swi4"=0.275,"sni4"=0.06,"pen4"=175,"nkrw4"=2,"nkrn4"=2,"npe4"=2,"thre4"=5e-2,"npnt4"=100}
facie5={"permx5"=2120000,"permz5"=2120000,"poro5"=0.39,"disperc5"=0,"swi5"=0.23,"sni5"=0.01,"pen5"=170,"nkrw5"=2,"nkrn5"=2,"npe5"=2,"thre5"=5e-2,"npnt5"=100}
facie6={"permx6"=2500000,"permz6"=2500000,"poro6"=0.42,"disperc6"=0,"swi6"=0.1742,"sni6"=0,"pen6"=163.2,"nkrw6"=2,"nkrn6"=2,"npe6"=2,"thre6"=5e-2,"npnt6"=100}

# Set the saturation functions
krw="(max(0, (sw - swi) / (1 - swi))) ** nkrw"             #Wetting rel perm saturation function [-]
krn="(max(0, (1 - sw - sni) / (1 - sni))) ** nkrn"         #Non-wetting rel perm saturation function [-]
cap="pen * ((sw-swi) / (1-swi)) ** (-(1.0 / npen))"        #Capillary pressure saturation function [Pa]

# Everest
min_realizations_success = 0 # Minimum number of simulations that must have succeeded for the simulation to be regarded as a success
max_function_evaluations = 200000 # Maximum number of simulations
rng = 7 # Set a specific seed for reproducibility; a value of 0 means no seed (rng for everest and random_seed for ert)
cores = 50 # Maximum number of simulations running in parallel
maxtime = 3600 # Maximum runtime in seconds of a realization; a value of 0 means unlimited runtime
delete = true # Delete large files?
monotonic = true # Only consider monotonic values, e.g, increasing entry pressure with decreasing sand size
popsize = 200 # Population size
perm5 = [2200e3, 1120e3, 2500e3, 20]
swi5 =  [  0.23,   0.17,   0.27,  4]
sni5 =  [  0.01,   0.01,   0.06,  6]
pen5 =  [   170,    164,    175, 10]
