# pofff -i everest_iter_3.toml -o everest_iter_3 -m everest -t 24,48,72,96,120
# Set the full path to the flow executable and flags
flow="flow --newton-min-iterations=1 --solver-max-restarts=20 --time-step-control=newtoniterationcount --solver-growth-factor=1.6 --linear-solver=cpr_trueimpes --time-step-control-growth-rate=1.1 --solver-restart-factor=0.5 --time-step-control-decay-rate=0.65 --enable-opm-rst-file=true"

# Set the model parameters
grid="corner-point" # Type of grid (cartesian, tensor, or corner-point)
thickness="final" # Thickness maps
mult_thickness=1 # Thickness multiplier
x=[140] # If cartesian, number of x cells [-]; otherwise, variable array of x-refinement
z=[7,5,5,5,5,5,5,8,10,9,5] # If cartesian, number of z cells [-]; if tensor, variable array of z-refinement; if corner-point, fix array of z-refinement (18 entries)
temperature=[20, 20] # Temperature bottom and top rig [C]
pressure=104900 # Pressure at the datum [Pa]           
diffusion=[1e-9, 2e-8] # Diffusion (in liquid and gas) [m^2/s]
sources=[[0.9, 0.005, 0.3], [1.7, 0.005, 0.7]] # Source positions: x, y, and z coordinates [m], source 1 to 2

# Schedule: 1) injection time [s], 2) time step size to write results [s], 3) injection rate [kg/s] (source1), and 4) injection rate [kg/s] (source2)
inj=[[8100, 8100, 3E-7, 0, '1e-2 3e-4 1e-20 1e-20 1.6 0.2 0.65 1.1'], 
[10200, 10200, 3E-7, 3E-7, '1e-2 1e-4 1e-20 1e-20 1.6 0.2 0.65 1.1'], 
[68100, 68100, 0, 0, '1e-2 1e-3 1e-20 1e-20 1.6 0.2 0.65 1.1'], 
[345600, 86400, 0, 0, '1e-2 1e-2 1e-20 1e-20 1.6 0.2 0.65 1.1']]

# Facie Properties
facie1={"PERMX1"=62000,"PERMZ1"=62000,"PORO1"=0.37,"DISPERC1"=0,"SWI1"=0.3425,"SNI1"=0.25,"PEN1"=1900,"NKRW1"=2,"NKRN1"=2,"NPE1"=2,"THRE1"=5e-2,"NPNT1"=100}
facie2={"PERMX2"=152000,"PERMZ2"=152000,"PORO2"=0.38,"DISPERC2"=0,"SWI2"=0.32,"SNI2"=0.2,"PEN2"=950,"NKRW2"=2,"NKRN2"=2,"NPE2"=2,"THRE2"=5e-2,"NPNT2"=100}
facie3={"PERMX3"=428000,"PERMZ3"=428000,"PORO3"=0.40,"DISPERC3"=0,"SWI3"=0.293,"SNI3"=0.077,"PEN3"=185,"NKRW3"=2,"NKRN3"=2,"NPE3"=2,"THRE3"=5e-2,"NPNT3"=100}
facie4={"PERMX4"=1120000,"PERMZ4"=1120000,"PORO4"=0.39,"DISPERC4"=0,"SWI4"=0.275,"SNI4"=0.06,"PEN4"=175,"NKRW4"=2,"NKRN4"=2,"NPE4"=2,"THRE4"=5e-2,"NPNT4"=100}
facie5={"PERMX5"=2120000,"PERMZ5"=2120000,"PORO5"=0.39,"DISPERC5"=0,"SWI5"=0.23,"SNI5"=0.01,"PEN5"=140,"NKRW5"=2,"NKRN5"=2,"NPE5"=2,"THRE5"=5e-2,"NPNT5"=100}
facie6={"PERMX6"=2500000,"PERMZ6"=2500000,"PORO6"=0.42,"DISPERC6"=0,"SWI6"=0.1742,"SNI6"=0,"PEN6"=163.2,"NKRW6"=2,"NKRN6"=2,"NPE6"=2,"THRE6"=5e-2,"NPNT6"=100}

# Set the saturation functions
krw="(max(0, (sw - swi) / (1 - swi))) ** nkrw"             #Wetting rel perm saturation function [-]
krn="(max(0, (1 - sw - sni) / (1 - sni))) ** nkrn"         #Non-wetting rel perm saturation function [-]
cap="pen * ((sw-swi) / (1-swi)) ** (-(1.0 / npen))"        #Capillary pressure saturation function [Pa]

# Everest
min_realizations_success = 0 # Minimum number of simulations that must have succeeded for the simulation to be regarded as a success.
max_function_evaluations = 200000 # Maximum number of simulations
random_seed = 7 # Set a specific seed for reproducibility; a value of 0 means no seed
cores = 50 # Maximum number of simulations running in parallel
maxtime = 3600 # Maximum runtime in seconds of a realization; a value of 0 means unlimited runtime
delete = true # Delete large files?
monotonic = true # Only consider monotonic values, e.g, increasing entry pressure with decreesing sand size
popsize = 200 # Population size
PERM5 = [2200E3, 1120E3, 2500E3, 20]
SWI5 =  [  0.23,   0.17,   0.27,  4]
SNI5 =  [  0.01,   0.01,   0.06,  6]
PEN5 =  [   170,    164,    175, 10]
